### ISSUE TITLE
Error Building GiN

### ISSUE THREAD

**Issue by tmtabor** [jaidevjoshi83/GiN#98]
I tried to build GiN today and got the following error:

```
#16 199.4 Traceback (most recent call last):
#16 199.4   File "/opt/conda/bin/jupyter-nbextension", line 10, in <module>
#16 199.4     sys.exit(main())
#16 199.4   File "/opt/conda/lib/python3.9/site-packages/jupyter_core/application.py", line 264, in launch_instance
#16 199.4     return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
#16 199.4   File "/opt/conda/lib/python3.9/site-packages/traitlets/config/application.py", line 978, in launch_instance
#16 199.4     app.start()
#16 199.4   File "/opt/conda/lib/python3.9/site-packages/notebook/nbextensions.py", line 980, in start
#16 199.4     super().start()
#16 199.4   File "/opt/conda/lib/python3.9/site-packages/jupyter_core/application.py", line 253, in start
#16 199.4     self.subapp.start()
#16 199.4   File "/opt/conda/lib/python3.9/site-packages/notebook/nbextensions.py", line 708, in start
#16 199.4     self.install_extensions()
#16 199.4   File "/opt/conda/lib/python3.9/site-packages/notebook/nbextensions.py", line 679, in install_extensions
#16 199.4     full_dests = install(self.extra_args[0],
#16 199.4   File "/opt/conda/lib/python3.9/site-packages/notebook/nbextensions.py", line 203, in install_nbextension_python
#16 199.4     m, nbexts = _get_nbextension_metadata(module)
#16 199.4   File "/opt/conda/lib/python3.9/site-packages/notebook/nbextensions.py", line 1114, in _get_nbextension_metadata
#16 199.4     m = import_item(module)
#16 199.4   File "/opt/conda/lib/python3.9/site-packages/traitlets/utils/importstring.py", line 38, in import_item
#16 199.4     return __import__(parts[0])
#16 199.4   File "/opt/conda/lib/python3.9/site-packages/GiN/__init__.py", line 14, in <module>
#16 199.4     import authwidget
#16 199.4 ModuleNotFoundError: No module named 'authwidget'
```

I suspect that __init__.py line 14 needs to change to import `.authwidget` rather than `authwidget` since there's no guarantee that GiN/GiN will be on the PYTHONPATH.

**Comment by jaidevjoshi83** [comment]
Thanks for pointing this out, I changed this import to the dev branch, and it will be merged soon. thank you.
